[package]
name = "derive"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.8"
synstructure = "0.12.3"
quote = "1.0.2"
